export const siteConfig = {
  name: "Aditya Sharma",
  title: "Aditya Sharma | Front-end developer",
  description:
    "Hello, I'm Aditya. I am front-end developer from India. I enjoy building sites and apps. My focus is React (Next.js).",
  keywords: [
    "Aditya Sharma",
    "Front-end developer",
    "Back-end developer",
    "India",
    "React",
    "Next.js",
    "Web development",
    "Front-end",
    "UI/UX",
    "Responsive design",
    "JavaScript",
    "HTML",
    "CSS",
    "Portfolio",
    "Projects",
    "Website",
    "Web applications",
    "Developer",
    "Code",
    "Programming",
    "Tech enthusiast",
  ],
  creator: "Aditya Sharma",
  url: "#",
  contact: {
    email: "john@doe.com",
    linkedin: "#",
    github: "#",
  },
  links: {
    contactForm: "/#contact",
    linkedin: "#",
    github: "#",
    mailTo: "mailto:john@doe.com",
    cvPdf: "/john-doe-cv.pdf",
    sohailYoutube: "",
  },
};
