export const siteConfig = {
  name: "Aditya Sharma",
  title: "Aditya Sharma | Front-end developer",
  description:
    "Hello, I'm Aditya. I am front-end developer from India. I enjoy building sites and apps. My focus is React (Next.js).",
  keywords: [
    "Aditya Sharma",
    "Front-end developer",
    "Back-end developer",
    "India",
    "React",
    "Next.js",
    "Web development",
    "Front-end",
    "UI/UX",
    "Responsive design",
    "JavaScript",
    "HTML",
    "CSS",
    "Portfolio",
    "Projects",
    "Website",
    "Web applications",
    "Developer",
    "Code",
    "Programming",
    "Tech enthusiast",
  ],
  creator: "Aditya Sharma",
  url: "#",
  contact: {
    email: "adityasharma626367@gmail.com",
    linkedin: "https://www.linkedin.com/in/adiityasharma",
    github: "https://github.com/adiityasharma",
  },
  links: {
    contactForm: "/#contact",
    linkedin: "https://www.linkedin.com/in/adiityasharma",
    github: "https://github.com/adiityasharma",
    mailTo: "mailto:adityasharma626367@gmail.com",
    cvPdf: "/Aditya_Sharma_Resume.pdf",
  },
};
